# Generated by Django 4.2.1 on 2023-06-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40)),
                ('product_type', models.CharField(max_length=40)),
                ('product_desc', models.TextField(max_length=40)),
                ('product_category', models.CharField(max_length=40)),
                ('product_image', models.ImageField(default='null.jpg', upload_to='images')),
            ],
        ),
    ]
