# Generated by Django 4.2.1 on 2023-06-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
    ]
