# Generated by Django 4.2.1 on 2023-06-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
