# Generated by Django 4.2.1 on 2023-06-12 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0004_cart_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=40)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=10)),
                ('cartid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.cart')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.users_registration')),
            ],
        ),
    ]
